use db;

CREATE TABLE USER(
    ID varchar(36)  ,
    FIRST_NAME varchar(36),
    LAST_NAME varchar(36),
    EMAIL_ID varchar(40),
    PRIMARY KEY(ID)
);


CREATE TABLE PAYMENT_METHOD (
    ID MEDIUMINT NOT NULL AUTO_INCREMENT, 
    PAYMENT_TYPE varchar(15),
    PAYMENT_TYPE_ID varchar(36),
    PRIMARY KEY (ID)
);


CREATE TABLE USER_PAYMENT_METHOD (
    PAYMENT_METHOD_ID MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID varchar(36) ,
    PAYMENT_TYPE varchar(15),
    PAYMENT_TYPE_ID varchar(36),
    UNIQUE KEY (`USER_ID`,`PAYMENT_TYPE`,`PAYMENT_TYPE_ID`),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE PAYMENT(
    ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    USER_ID varchar(36),
    PAYEE_ID  varchar(36),
    PAYMENT_METHOD_ID  varchar(36),
    CURRENCY varchar(20),
    AMOUNT DECIMAL(8,2),
    RISK_SCORE INT,
    PAYMENT_STATUS ENUM('SUCCESS', 'FAILED'),
    PRIMARY KEY (ID)
);